table Orders
	lineageTag: 44c17e85-b9e3-4285-9b43-8239dd5ec5d7

	column 'Row ID'
		dataType: int64
		formatString: 0
		lineageTag: c3ae5e8e-4767-42c2-9628-91e5d93ecdf2
		summarizeBy: count
		sourceColumn: Row ID

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: e3a0b72e-a3c4-4c1c-b4b0-60aca785082f
		summarizeBy: none
		sourceColumn: Order ID

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 765337ab-9d9e-4cb2-a52e-ef917fcbc51c
		summarizeBy: none
		sourceColumn: Order Date

		variation Variation
			isDefault
			relationship: fec73313-ede8-4301-a680-fb0f69a0803d
			defaultHierarchy: LocalDateTable_ab806d66-b730-49d9-921d-015ee0262321.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ship Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: dd337859-a134-484d-8a8c-5115440ac556
		summarizeBy: none
		sourceColumn: Ship Date

		variation Variation
			isDefault
			relationship: be52d9a9-202b-4136-a453-16c6ae397386
			defaultHierarchy: LocalDateTable_763c5db4-6761-4996-a12e-ed7d59f1fa09.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ship Mode'
		dataType: string
		lineageTag: 6d1eb650-fdde-449e-ad6c-8a03037133cb
		summarizeBy: none
		sourceColumn: Ship Mode

		annotation SummarizationSetBy = Automatic

	column 'Customer ID'
		dataType: string
		lineageTag: 6af50b8e-d8f1-4e17-8316-08d22b1f2744
		summarizeBy: none
		sourceColumn: Customer ID

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: 12584431-361d-4927-ae96-0704987c4896
		summarizeBy: none
		sourceColumn: Customer Name

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: d2dc179c-bfb5-4286-86c7-13b32d355828
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column Country/Region
		dataType: string
		lineageTag: e7670521-279c-4013-aa2d-0e20c41cb032
		summarizeBy: none
		sourceColumn: Country/Region

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 8b7b5a5c-a223-44e2-b806-fc8fe9124aed
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: a1a340d0-f6e9-4cf0-96ad-33e44940e837
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: int64
		formatString: 0
		lineageTag: f6b97877-a3df-4730-8559-caa15de9dbad
		summarizeBy: count
		sourceColumn: Postal Code

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: fa20de2c-694b-45f1-9fd0-0aa89fcea260
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: string
		lineageTag: 8ea68735-e053-4e87-b78f-cc7333c53c8c
		summarizeBy: none
		sourceColumn: Product ID

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: ee556ebb-23a5-4a07-93c4-da52dddeb5a7
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Sub-Category
		dataType: string
		lineageTag: e8f68e7d-7c93-477b-a2c5-c1ed526395b8
		summarizeBy: none
		sourceColumn: Sub-Category

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: ffba6411-d3e9-45ef-b041-00a5371c7ed8
		summarizeBy: none
		sourceColumn: Product Name

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		lineageTag: 6fda70dd-e51f-40d0-8c80-af0e3c76be39
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: 4e671d68-ffb1-4c8e-ad87-62d17881e82c
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: double
		lineageTag: ac8a4ab3-dc14-4868-9c4f-bcb4ab8e74eb
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Profit
		dataType: double
		lineageTag: 091b880b-af68-4428-abea-c5d08bf61bec
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Orders = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("G:\.shortcut-targets-by-id\1Wd_VA61kYWzAXLkSnCnmq-WAqAK9epVb\Material\5- Power BI\S1\Sample - Superstore.xlsx"), null, true),
				    Orders_Sheet = Source{[Item="Orders",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Orders_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Row ID", Int64.Type}, {"Order ID", type text}, {"Order Date", type date}, {"Ship Date", type date}, {"Ship Mode", type text}, {"Customer ID", type text}, {"Customer Name", type text}, {"Segment", type text}, {"Country/Region", type text}, {"City", type text}, {"State", type text}, {"Postal Code", Int64.Type}, {"Region", type text}, {"Product ID", type text}, {"Category", type text}, {"Sub-Category", type text}, {"Product Name", type text}, {"Sales", type number}, {"Quantity", Int64.Type}, {"Discount", type number}, {"Profit", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

